export const floridaCounties = [
    {county_id:"1" ,county_name:"Alachua"},
    {county_id:"8" ,county_name:"Baker"},
    {county_id:"9" ,county_name:"Bay"},
    {county_id:"10" ,county_name:"Bradford"},
    {county_id:"11" ,county_name:"Brevard"},
    {county_id:"12" ,county_name:"Broward"},
    {county_id:"13" ,county_name:"Calhoun"},
    {county_id:"14" ,county_name:"Charlotte"},
    {county_id:"15" ,county_name:"Citrus"},
    {county_id:"16" ,county_name:"Clay"},
    {county_id:"17" ,county_name:"Collier"},
    {county_id:"18" ,county_name:"Columbia"},
    {county_id:"19" ,county_name:"DeSoto"},
    {county_id:"20" ,county_name:"Dixie"},
    {county_id:"21" ,county_name:"Duval"},
    {county_id:"22" ,county_name:"Escambia"},
    {county_id:"23" ,county_name:"Flagler"},
    {county_id:"24" ,county_name:"Franklin"},
    {county_id:"25" ,county_name:"Gadsden"},
    {county_id:"26" ,county_name:"Gilchrist"},
    {county_id:"27" ,county_name:"Glades"},
    {county_id:"28" ,county_name:"Gulf"},
    {county_id:"74" ,county_name:"Hamilton"},
    {county_id:"73" ,county_name:"Hardee"},
    {county_id:"72" ,county_name:"Hendry"},
    {county_id:"71" ,county_name:"Hernando"},
    {county_id:"70" ,county_name:"Highlands"},
    {county_id:"69" ,county_name:"Hillsborough"},
    {county_id:"68" ,county_name:"Holmes"},
    {county_id:"67" ,county_name:"Indian River"},
    {county_id:"66" ,county_name:"Jackson"},
    {county_id:"65" ,county_name:"Jefferson"},
    {county_id:"64" ,county_name:"Lafayette"},
    {county_id:"63" ,county_name:"Lake"},
    {county_id:"62" ,county_name:"Lee"},
    {county_id:"61" ,county_name:"Leon"},
    {county_id:"60" ,county_name:"Levy"},
    {county_id:"59" ,county_name:"Liberty"},
    {county_id:"58" ,county_name:"Madison"},
    {county_id:"57" ,county_name:"Manatee"},
    {county_id:"56" ,county_name:"Marion"},
    {county_id:"55" ,county_name:"Martin"},
    {county_id:"54" ,county_name:"Miami-Dade"},
    {county_id:"53" ,county_name:"Monroe"},
    {county_id:"52" ,county_name:"Nassau"},
    {county_id:"51" ,county_name:"Okaloosa"},
    {county_id:"50" ,county_name:"Okeechobee"},
    {county_id:"49" ,county_name:"Orange"},
    {county_id:"48" ,county_name:"Osceola"},
    {county_id:"47" ,county_name:"Palm Beach"},
    {county_id:"46" ,county_name:"Pasco"},
    {county_id:"45" ,county_name:"Pinellas"},
    {county_id:"43" ,county_name:"Polk"},
    {county_id:"42" ,county_name:"Putnam"},
    {county_id:"41" ,county_name:"St. Johns"},
    {county_id:"40" ,county_name:"St. Lucie"},
    {county_id:"39" ,county_name:"Santa Rosa"},
    {county_id:"38" ,county_name:"Sarasota"},
    {county_id:"37" ,county_name:"Seminole"},
    {county_id:"36" ,county_name:"Sumter"},
    {county_id:"35" ,county_name:"Suwannee"},
    {county_id:"34" ,county_name:"Taylor"},
    {county_id:"33" ,county_name:"Union"},
    {county_id:"32" ,county_name:"Volusia"},
    {county_id:"31" ,county_name:"Wakulla"},
    {county_id:"30" ,county_name:"Walton"},
    {county_id:"29" ,county_name:"Washington"},    
]

export const propertiesType = [
    {property_type_id :'1' ,property_type_name:"Single Family"},
    {property_type_id :'2' ,property_type_name:"Townhouse"},
    {property_type_id :'3' ,property_type_name:"Condo"},
    {property_type_id :'4' ,property_type_name:"Multifamily"},
    {property_type_id :'5' ,property_type_name:"Vacant Land"}
]